image:
  repository: rabbitmq
  pullPolicy: IfNotPresent
  tag: 3.10.1@sha256:b7b61de711694729b32bfbea88756c40fe00ef88e62220eda08ca400c407c8a4

controller:
  # -- Set the controller type.
  # Valid options are deployment, daemonset or statefulset
  type: statefulset
  # -- Number of desired pods
  replicas: 1
  # -- Set the controller upgrade strategy
  # For Deployments, valid values are Recreate (default) and RollingUpdate.
  # For StatefulSets, valid values are OnDelete and RollingUpdate (default).
  # DaemonSets ignore this.
  strategy: RollingUpdate
  rollingUpdate:
    # -- Set deployment RollingUpdate max unavailable
    unavailable: 1
    # -- Set deployment RollingUpdate max surge
    surge:
    # -- Set statefulset RollingUpdate partition
    partition:
  # -- ReplicaSet revision history limit
  revisionHistoryLimit: 3

service:
  main:
    ports:
      main:
        port: 5672
        targetPort: 5672

securityContext:
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsGroup: 0

volumeClaimTemplates:
  config:
    enabled: true
    mountPath: "/etc/rabbitmq"
  data:
    enabled: true
    mountPath: "/var/lib/rabbitmq/mnesia/"

# -- Probe configuration
# -- [[ref]](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)
# @default -- See below
probes:
  # -- Liveness probe configuration
  # @default -- See below
  liveness:
    # -- Enable the liveness probe
    enabled: true
    # -- Set this to `true` if you wish to specify your own livenessProbe
    custom: true
    # -- The spec field contains the values for the default livenessProbe.
    # If you selected `custom: true`, this field holds the definition of the livenessProbe.
    # @default -- See below
    spec:
      exec:
        command:
          - sh
          - -c
          - "until rabbitmq-diagnostics -q ping; do sleep 2; done"

  # -- Readiness probe configuration
  # @default -- See below
  readiness:
    # -- Enable the readiness probe
    enabled: true
    # -- Set this to `true` if you wish to specify your own readinessProbe
    custom: true
    # -- The spec field contains the values for the default readinessProbe.
    # If you selected `custom: true`, this field holds the definition of the readinessProbe.
    # @default -- See below
    spec:
      exec:
        command:
          - sh
          - -c
          - "until rabbitmq-diagnostics check_running; do sleep 2; done"
  # -- Startup probe configuration
  # @default -- See below
  startup:
    # -- Enable the startup probe
    enabled: true
    custom: true
    # -- The spec field contains the values for the default livenessProbe.
    # If you selected `custom: true`, this field holds the definition of the livenessProbe.
    # @default -- See below
    spec:
      exec:
        command:
          - sh
          - -c
          - "until rabbitmq-diagnostics check_running; do sleep 2; done"

rabbitmqPassword: "guest"
rabbitmqUsername: "guest"
rabbitmqVhost: "/"
rabbitmqPort: 5672
