{{- $values := .Values }}
{{- $namespace := ( printf "ix-%s" .Release.Name ) }}
{{- if or ( not .Values.ingressClass.enabled ) ( and ( .Values.ingressClass.enabled ) ( .Values.ingressClass.isDefaultClass ) ) }}
{{- $namespace = "default" }}
{{- end }}

{{ range $index, $middlewareData := .Values.middlewares.themePark }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $middlewareData.name }}
  namespace: {{ $namespace }}
spec:
  plugin:
    themePark:
      app: {{ $middlewareData.appName }}
      theme: {{ $middlewareData.themeName }}
      {{- if $middlewareData.enableBaseUrl }}
      baseUrl: {{ $middlewareData.baseUrl }}
      {{- end -}}
{{ end }}
