apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  /etc/rabbitmq/config.conf: |-
        default_vhost = {{ ( .Values.rabbitmqVhost | default "/" ) | b64enc | quote }}
        default_user = {{ ( .Values.rabbitmqPassword | default "guest" ) | b64enc | quote }}
        default_pass = {{ ( .Values.rabbitmqUsername | default "guest" ) | b64enc | quote }}
        listeners.tcp.default = {{ ( .Values.rabbitmqPort | default 5672 ) }}